// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PITXOnlineBooking;
using PITXOnlineBooking.Data;

#nullable disable

namespace PITXOnlineBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116163521_FixedLinuxProblem")]
    partial class FixedLinuxProblem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PITXOnlineBooking.Models.BookedTripModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("DateBooked")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datebooked");

                    b.Property<int>("InsuranceType")
                        .HasColumnType("int")
                        .HasColumnName("insurancetype");

                    b.Property<int>("PassengerNo")
                        .HasColumnType("int")
                        .HasColumnName("passengerno");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticketno");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("totalprice");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("tripid");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("bookedtrip");
                });

            modelBuilder.Entity("PITXOnlineBooking.Models.BusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusLogo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("buslogo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("ImgInside")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("imginside");

                    b.Property<string>("ImgOutside")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("imgoutside");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("operator");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("bus");
                });

            modelBuilder.Entity("PITXOnlineBooking.Models.BusTripModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int")
                        .HasColumnName("busid");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departure");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destination");

                    b.Property<decimal>("TotalTripTime")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("totaltriptime");

                    b.Property<int>("TripPrice")
                        .HasColumnType("int")
                        .HasColumnName("tripprice");

                    b.HasKey("Id");

                    b.ToTable("bustrip");
                });

            modelBuilder.Entity("PITXOnlineBooking.Models.GCashModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("AvailableBalance")
                        .HasColumnType("int")
                        .HasColumnName("availablebalance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.HasKey("Id");

                    b.ToTable("gcash");
                });

            modelBuilder.Entity("PITXOnlineBooking.Models.InsuranceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("package");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("insurance");
                });

            modelBuilder.Entity("PITXOnlineBooking.Models.PassengerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("agegroup");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.ToTable("passenger");
                });

            modelBuilder.Entity("PITXOnlineBooking.Models.TripModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrivaltime");

                    b.Property<string>("Bay")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bay");

                    b.Property<int>("BusTripId")
                        .HasColumnType("int")
                        .HasColumnName("bustripid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departuretime");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destination");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("gate");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<TimeSpan>("TotalTripTime")
                        .HasColumnType("TIME")
                        .HasColumnName("totaltriptime");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tripdate");

                    b.Property<string>("TripNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tripno");

                    b.HasKey("Id");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("PITXOnlineBooking.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("agegroup");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lastname");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("mobile");

                    b.Property<int>("PassengersId")
                        .HasColumnType("int")
                        .HasColumnName("passengersid");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("PITXOnlineBooking.PayMayaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("AvailBalance")
                        .HasColumnType("int")
                        .HasColumnName("availbalance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.HasKey("Id");

                    b.ToTable("paymaya");
                });
#pragma warning restore 612, 618
        }
    }
}
